<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.fanbei.borrowCash"
           tests="11"
           failures="3"
           errors="0"
           skipped="0"
           time="0.415">
  <properties />
            <testcase name="getConfirmBorrowInfo" time="0.026" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest">
                <failure type="java.lang.AssertionError"
                  message="expected [1005] but found [1015]"
              >
<![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.fanbei.borrowCash.GetConfirmBorrowInfoTest.getConfirmBorrowInfo(GetConfirmBorrowInfoTest.java:68)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
            <testcase name="getConfirmBorrowInfo" time="0.026" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest">
                <failure type="java.lang.AssertionError"
                  message="expected [1005] but found [1015]"
              >
<![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.fanbei.borrowCash.GetConfirmBorrowInfoTest.getConfirmBorrowInfo(GetConfirmBorrowInfoTest.java:68)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
            <testcase name="getConfirmBorrowInfo" time="0.037" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest">
                <failure type="java.lang.AssertionError"
                  message="expected [2008] but found [1117]"
              >
<![CDATA[java.lang.AssertionError: expected [2008] but found [1117]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  org.testng.Assert.assertEquals(Assert.java:186)
  com.fanbei.borrowCash.GetConfirmBorrowInfoTest.getConfirmBorrowInfo(GetConfirmBorrowInfoTest.java:68)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
  org.testng.SuiteRunner.run(SuiteRunner.java:254)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="getConfirmBorrowInfo" time="0.049" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
                <testcase name="getConfirmBorrowInfo" time="0.055" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
                <testcase name="getConfirmBorrowInfo" time="0.032" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
                <testcase name="getConfirmBorrowInfo" time="0.035" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
                <testcase name="getConfirmBorrowInfo" time="0.040" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
                <testcase name="getConfirmBorrowInfo" time="0.044" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
                <testcase name="getConfirmBorrowInfo" time="0.030" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
                <testcase name="getConfirmBorrowInfo" time="0.041" classname="com.fanbei.borrowCash.GetConfirmBorrowInfoTest" />
      
</testsuite>
